#!/usr/bin/env python3
"""Generate the method-provenance documentation from the runtime registry."""

from __future__ import annotations

import argparse
from pathlib import Path

from robustcov.provenance import (
    METHOD_PROVENANCE,
    REFERENCE_CATALOG,
    STATUS_LABELS,
    iter_method_provenance,
)


def _reference_links(keys: tuple[str, ...]) -> str:
    return ", ".join(
        f"`{REFERENCE_CATALOG[key].short} <{REFERENCE_CATALOG[key].url}>`__"
        for key in keys
    )


def render() -> str:
    lines = [
        ".. Generated by scripts/generate_method_provenance.py. Do not edit by hand.",
        "",
        "Method provenance registry",
        "--------------------------",
        "",
        "The status describes the origin of the *method*, not the amount of software",
        "engineering involved. No current public entry is marked as an original",
        "methodological contribution.",
        "",
        ".. method-provenance-body-start",
        "",
    ]
    families = sorted({entry.family for entry in METHOD_PROVENANCE.values()}, key=str.lower)
    for family in families:
        lines.extend([family, "~" * len(family), ""])
        for entry in iter_method_provenance(family=family):
            anchor = entry.name.lower().replace("_", "-")
            lines.extend([
                f".. _method-provenance-{anchor}:",
                "",
                f"``{entry.name}``",
                "^" * (len(entry.name) + 4),
                "",
                f"**Status:** {STATUS_LABELS[entry.status]}",
                "",
                f"**Method:** {entry.summary}",
                "",
                f"**Primary references:** {_reference_links(entry.references)}",
                "",
                f"**robustcov contribution:** {entry.robustcov_contribution}",
                "",
                f"**Implementation notes:** {entry.implementation_notes}",
                "",
            ])
            if entry.aliases:
                aliases = ", ".join(f"``{alias}``" for alias in entry.aliases)
                lines.extend([f"**Public aliases:** {aliases}", ""])
    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("docs/_generated/method_provenance.inc"),
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render()
    if args.check:
        current = args.output.read_text(encoding="utf-8") if args.output.exists() else ""
        if current != content:
            raise SystemExit(f"{args.output} is stale; run scripts/generate_method_provenance.py")
        print(f"method provenance is current: {args.output}")
        return
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(content, encoding="utf-8")
    print(f"wrote {args.output}")


if __name__ == "__main__":
    main()
