#!/usr/bin/env python3
"""Generate or verify the focused release-candidate evidence snapshot.

The snapshot covers the numerical areas changed in the current release cycle:
FastMCD calibration/diagnostics, the shared covariance accuracy and speed
profiles, and robust SHAP/LIME explanation references. Unrelated galleries are
not regenerated by this command.
"""

from __future__ import annotations

import argparse
import csv
from datetime import datetime, timezone
import hashlib
import importlib.metadata
import json
import os
from pathlib import Path
import platform
import subprocess
import sys
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_BENCHMARK_DIR = ROOT / "docs" / "_static" / "benchmarks"
DEFAULT_EXAMPLE_DIR = ROOT / "docs" / "_static" / "examples"
DEFAULT_MANIFEST = ROOT / "docs" / "_static" / "release_evidence.json"


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _source_files() -> list[Path]:
    files = [ROOT / "pyproject.toml", ROOT / "CMakeLists.txt"]
    for base in (ROOT / "robustcov", ROOT / "src"):
        for path in base.rglob("*"):
            if path.is_file() and path.suffix in {".py", ".json", ".cpp", ".hpp", ".h"}:
                files.append(path)
    return sorted(set(files))


def _source_tree_sha256() -> str:
    digest = hashlib.sha256()
    for path in _source_files():
        relative = path.relative_to(ROOT).as_posix().encode("utf-8")
        digest.update(relative)
        digest.update(b"\0")
        digest.update(path.read_bytes())
        digest.update(b"\0")
    return digest.hexdigest()


def _version(distribution: str) -> str | None:
    try:
        return importlib.metadata.version(distribution)
    except importlib.metadata.PackageNotFoundError:
        return None


def _git_revision() -> str:
    try:
        return subprocess.check_output(
            ["git", "rev-parse", "HEAD"], cwd=ROOT, text=True
        ).strip()
    except (OSError, subprocess.CalledProcessError):
        return "unknown"


def _run(command: list[str], *, env: dict[str, str], capture: Path | None = None) -> None:
    print("+", " ".join(command))
    completed = subprocess.run(
        command,
        cwd=ROOT,
        env=env,
        text=True,
        capture_output=True,
        check=False,
    )
    if capture is not None:
        capture.parent.mkdir(parents=True, exist_ok=True)
        capture.write_text(completed.stdout, encoding="utf-8")
    if completed.returncode:
        sys.stdout.write(completed.stdout)
        sys.stderr.write(completed.stderr)
        raise SystemExit(completed.returncode)


def _read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as stream:
        return list(csv.DictReader(stream))


def _row(rows: list[dict[str, str]], key: str, value: str) -> dict[str, str]:
    return next(row for row in rows if row[key] == value)


def _artifact_paths(benchmark_dir: Path, example_dir: Path) -> list[Path]:
    return [
        benchmark_dir / "small_sample.csv",
        benchmark_dir / "small_sample_summary.csv",
        benchmark_dir / "small_sample_rank.png",
        benchmark_dir / "speed.csv",
        benchmark_dir / "speed.png",
        benchmark_dir / "statistical_validation.json",
        example_dir / "robust_explanations_iris.json",
        example_dir / "robust_explanations_iris.png",
        example_dir / "robust_explanations_iris_output.txt",
    ]


def _relative(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def generate(
    *,
    benchmark_dir: Path,
    example_dir: Path,
    manifest_path: Path,
    source_revision: str,
) -> None:
    benchmark_dir.mkdir(parents=True, exist_ok=True)
    example_dir.mkdir(parents=True, exist_ok=True)

    python = sys.executable
    env = os.environ.copy()
    env.update(
        {
            "PYTHONPATH": str(ROOT),
            "OPENBLAS_NUM_THREADS": "1",
            "MKL_NUM_THREADS": "1",
            "OMP_NUM_THREADS": "2",
            "MPLBACKEND": "Agg",
        }
    )

    small_raw = benchmark_dir / "small_sample.csv"
    small_summary = benchmark_dir / "small_sample_summary.csv"
    small_plot = benchmark_dir / "small_sample_rank.png"
    speed_csv = benchmark_dir / "speed.csv"
    speed_plot = benchmark_dir / "speed.png"
    statistical_json = benchmark_dir / "statistical_validation.json"
    explanation_json = example_dir / "robust_explanations_iris.json"
    explanation_plot = example_dir / "robust_explanations_iris.png"
    explanation_output = example_dir / "robust_explanations_iris_output.txt"

    commands = [
        [
            python,
            "benchmarks/small_sample_heavy_tail.py",
            "--profile",
            "quick",
            "--repeat",
            "2",
            "--csv",
            _relative(small_raw),
        ],
        [
            python,
            "benchmarks/benchmark_summary.py",
            "--input",
            _relative(small_raw),
            "--csv",
            _relative(small_summary),
        ],
        [
            python,
            "examples/plot_benchmark_summary.py",
            "--input",
            _relative(small_summary),
            "--metric",
            "mean_rank",
            "--output",
            _relative(small_plot),
        ],
        [
            python,
            "benchmarks/speed_estimators.py",
            "--profile",
            "quick",
            "--repeat",
            "2",
            "--csv",
            _relative(speed_csv),
        ],
        [
            python,
            "examples/plot_speed_comparison.py",
            "--input",
            _relative(speed_csv),
            "--output",
            _relative(speed_plot),
        ],
        [
            python,
            "benchmarks/statistical_validation.py",
            "--json-output",
            _relative(statistical_json),
        ],
        [
            python,
            "examples/robust_explanations_iris.py",
            "--json-output",
            _relative(explanation_json),
            "--plot-output",
            _relative(explanation_plot),
        ],
    ]

    for command in commands[:-1]:
        _run(command, env=env)
    _run(commands[-1], env=env, capture=explanation_output)

    # csv.writer uses CRLF by default. Normalize committed evidence so
    # ``git diff --check`` remains meaningful on every platform.
    for csv_path in (small_raw, small_summary, speed_csv):
        csv_path.write_bytes(csv_path.read_bytes().replace(b"\r\n", b"\n"))

    summary_rows = _read_csv(small_summary)
    speed_rows = _read_csv(speed_csv)
    auto = _row(summary_rows, "method", "robustcov AutoRobustScatter")
    cauchy = _row(summary_rows, "method", "robustcov RegularizedCauchy")
    fastmcd = _row(summary_rows, "method", "robustcov FastMCD")
    mincovdet = _row(summary_rows, "method", "sklearn MinCovDet")
    fast_speed = next(
        row
        for row in speed_rows
        if row["workload"] == "classical_contamination"
        and row["method"] == "robustcov FastMCD"
    )
    sklearn_speed = next(
        row
        for row in speed_rows
        if row["workload"] == "classical_contamination"
        and row["method"] == "sklearn MinCovDet"
    )
    statistical = json.loads(statistical_json.read_text(encoding="utf-8"))
    explanation = json.loads(explanation_json.read_text(encoding="utf-8"))

    artifacts = {
        _relative(path): {"sha256": _sha256(path), "bytes": path.stat().st_size}
        for path in _artifact_paths(benchmark_dir, example_dir)
        if path.exists()
    }
    manifest: dict[str, Any] = {
        "schema_version": 1,
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "source_revision": source_revision,
        "source_tree_sha256": _source_tree_sha256(),
        "profile": {
            "small_sample": "quick, repeat=2",
            "speed": "quick, repeat=2",
            "thread_environment": {
                "OPENBLAS_NUM_THREADS": "1",
                "MKL_NUM_THREADS": "1",
                "OMP_NUM_THREADS": "2",
            },
        },
        "environment": {
            "python": platform.python_version(),
            "python_implementation": platform.python_implementation(),
            "python_compiler": platform.python_compiler(),
            "platform": platform.platform(),
            "machine": platform.machine(),
            "numpy": _version("numpy"),
            "scipy": _version("scipy"),
            "scikit_learn": _version("scikit-learn"),
            "shap": _version("shap"),
            "lime": _version("lime"),
            "matplotlib": _version("matplotlib"),
        },
        "commands": [" ".join(command) for command in commands],
        "key_results": {
            "small_sample": {
                "auto_robust_scatter": auto,
                "regularized_cauchy": cauchy,
                "fastmcd": fastmcd,
                "sklearn_mincovdet": mincovdet,
            },
            "classical_contamination_speed": {
                "fastmcd_seconds": float(fast_speed["median_seconds"]),
                "sklearn_mincovdet_seconds": float(sklearn_speed["median_seconds"]),
                "local_speed_ratio": float(sklearn_speed["median_seconds"])
                / float(fast_speed["median_seconds"]),
            },
            "statistical_validation": {
                "passed": statistical["passed"],
                "sklearn_reference": statistical["sklearn_reference"],
                "contamination_curve": statistical["contamination_curve"],
            },
            "robust_explanations_iris": explanation,
        },
        "artifacts": artifacts,
    }
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    print(f"wrote release evidence manifest: {_relative(manifest_path)}")


def check(*, manifest_path: Path) -> int:
    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        print(f"release evidence manifest is unreadable: {exc}", file=sys.stderr)
        return 1

    errors: list[str] = []
    if manifest.get("schema_version") != 1:
        errors.append("schema_version must be 1")
    expected_source = manifest.get("source_tree_sha256")
    actual_source = _source_tree_sha256()
    if expected_source != actual_source:
        errors.append(
            f"source tree digest differs: expected={expected_source}, actual={actual_source}"
        )
    artifacts = manifest.get("artifacts")
    if not isinstance(artifacts, dict) or not artifacts:
        errors.append("artifact manifest is empty")
    else:
        for relative, metadata in artifacts.items():
            path = ROOT / relative
            if not path.is_file():
                errors.append(f"missing artifact: {relative}")
                continue
            expected = metadata.get("sha256") if isinstance(metadata, dict) else None
            actual = _sha256(path)
            if expected != actual:
                errors.append(
                    f"artifact digest differs for {relative}: expected={expected}, actual={actual}"
                )
    key_results = manifest.get("key_results", {})
    statistical = key_results.get("statistical_validation", {}) if isinstance(key_results, dict) else {}
    if statistical.get("passed") is not True:
        errors.append("statistical validation is not recorded as passing")

    if errors:
        for error in errors:
            print(f"FAIL: {error}")
        return 1
    print(
        "release evidence is current:",
        manifest_path.relative_to(ROOT),
        f"({len(artifacts)} artifacts)",
    )
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--benchmark-dir", type=Path, default=DEFAULT_BENCHMARK_DIR)
    parser.add_argument("--example-dir", type=Path, default=DEFAULT_EXAMPLE_DIR)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--source-revision", default=None)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    benchmark_dir = args.benchmark_dir.resolve()
    example_dir = args.example_dir.resolve()
    manifest_path = args.manifest.resolve()
    if args.check:
        return check(manifest_path=manifest_path)
    generate(
        benchmark_dir=benchmark_dir,
        example_dir=example_dir,
        manifest_path=manifest_path,
        source_revision=args.source_revision or _git_revision(),
    )
    return check(manifest_path=manifest_path)


if __name__ == "__main__":
    raise SystemExit(main())
